theme: jekyll-theme-minimal

title: Allie Wyland
description: Allie's personal website
logo: Allison_Wyland.jpg

navbar:
  title: "awyland2 personal website"
  left:
  - text: "Home"
   href: index.md
  - text: "rblog"
   href: rmd-test-page.Rmd


